spring:
  application:
    name: casino

  cloud:
    azure:
      keyvault:
        secret:
          property-sources:
            - endpoint: https://nitrossecret.vault.azure.net

  datasource:
    url: ${mysqlurl}
    username: ${mysqluser}
    password: ${mysqlpassword}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: Blackjack
            client-secret: your-client-secret
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/Nitro


  flyway:
    enabled: true
    locations: classpath:db/migration # Default location for migration scripts
    baseline-on-migrate: false # Set to true to baseline an existing schema
    clean-disabled: false # Set to true to allow Flyway clean operation

server:
  port: 8081
